language: scala

env:
  - TEST_SUITE=coursera/week_1/example
  - TEST_SUITE=coursera/week_1/wikipedia
  - TEST_SUITE=coursera/week_2/stackoverflow
  - TEST_SUITE=coursera/week_4/timeusage


# Use container-based infrastructure
sudo: false

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

script:
   - "cd $TEST_SUITE && sbt test"
